# Generated by Django 5.2.4 on 2025-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_text_source_alter_test_text_alter_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='source_link',
            field=models.CharField(default='#', max_length=100),
            preserve_default=False,
        ),
    ]
