# Generated by Django 5.2.4 on 2025-07-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_test_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('tab_count', models.IntegerField(default=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='text',
            name='prolang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.programminglanguage'),
        ),
    ]
